# Change these first
owner: loke-60000 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: lokman.fr
    url: https://lokman.fr
  - name: gadget-lab.fr
    url: https://gadget-lab.fr
  - name: gadget-lab.net
    url: https://gadget-lab.net
  - name: Amadeus-gpt
    url: https://viktorchondria.com/
  - name: Searx
    url: https://search.gadget-lab.net
  - name: Jin-Joo
    url: https://www.jin-joo.fr/
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: IPv6 test
    url: forwardemail.net
    port: 80
    check: "tcp-ping"
    ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Loke-60000 Upptime
  introTitle: "**Lokman's Status Page**"
  introMessage: "Real-time monitoring of Lokman's projects and services, powered by GitHub Actions and Upptime."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: lokman
      href: https://lokman.fr

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
